### PR TITLE
feat: allow using notebook for storing templates

### PR DESCRIPTION
**Pull request by BeatLink**
This implements Feature Request #62

### CODE REVIEW

**Review by nishantwrp — CHANGES_REQUESTED** [review]
Hi @BeatLink, thanks for the pr. Can you go through https://github.com/joplin/plugin-templates/issues/12 once? This is a discussion about this we had before. And, the unit tests are failing too.

**Review by nishantwrp — CHANGES_REQUESTED** [review]
Hi @BeatLink, along with the code can you also update the documentation (README.md)?

**Comment by BeatLink** [comment]
Done

**Comment by nishantwrp** [comment]
Hi @BeatLink, will review this within this week.

**Comment by BeatLink** [comment]
Hi there. Any updates?

**Review by nishantwrp — COMMENTED** [review]
Hi @BeatLink, sorry for the delay. I've made some changes in this pull request and made another PR to your branch. Once you merge that we'll be good to go.

Link to the pull request - https://github.com/BeatLink/plugin-templates/pull/1

**Comment by BeatLink** [comment]
Looks good! Changes merged as requested.

**Review by nishantwrp — APPROVED** [review]
lgtm, thanks @BeatLink!

**Pull request merged**
