### PR TITLE
fix: improve error messages in case of invalid variable names

### LINKED ISSUE #29: Space and special characters in variable name leads to error
Spaces, German umlauts, special characters, leading numbers lead to errors in variable names.
grafik

Possibly check the variable names before parsing if only permitted characters (`a-zA-Z0-9`) are included? 

```
---
Änderung: enum(Einplanen, Ausplanen)
1nderung: text
Aenderung&Test: text

---
```

### PR DESCRIPTION
**Pull request by nishantwrp**
Fixes #29.

### CODE REVIEW

**Comment by nishantwrp** [comment]
Now, in the case of valid variable names, the plugin works as usual. But if there's an invalid variable name like `some var` or `some@var` etc. there is an error and the templates dialog is not shown.

Screenshot of the error message
Screenshot_20210815_002046

**Comment by CalebJohn** [comment]
Nice fix! Ideally you should perform a more direct check using a list of known bad characters as well. That way users don't have to guess and check to see if `(` is a special character or not. I don't think you need to do this immediately, but please either update this PR, or create an issue to track it.

**Comment by nishantwrp** [comment]
@CalebJohn, actually the problem is that there is no list as such that tells all of these characters are bad and others are good. That's also the reason why I check it directly with Handlebars. 

According to me, we can in general say all the users to not use any special character or space. This way they know that their variable name is surely valid.

**Comment by JackGruber** [comment]
>actually the problem is that there is no list as such that tells all of these characters are bad and others are good. 

How about just using the javascript naming rules? 

- Variable names cannot contain spaces.
- Variable names must begin with a letteror an underscore (`_`).
- Variable names can only contain letters, numbers, underscores.
- Variable names are case-sensitive.

**Comment by nishantwrp** [comment]
Maybe I'm wrong, but I think if we say that `Don't use special characters or spaces in the variable names with underscore as an exception` it'll do. Thoughts?

**Comment by CalebJohn** [comment]
> Maybe I'm wrong, but I think if we say that `Don't use special characters or spaces in the variable names with underscore as an exception` it'll do. Thoughts?

I think you're wrong here. Many users won't know what a "special" character is. Too be honest, if i saw that, i wouldn't be sure either. For example, i might use the variable name "variable-(1)". Which one of these is a special character?

I'm not suggesting you need to have a list of all "special" characters, but there are already characters that you know aren't allowed (see #29), these can be added to a list. You should still use your current code as a fallback check.

Does that make sense?

**Comment by nishantwrp** [comment]
So, if I correctly understand, you mean to use the list of known invalid characters for the purpose of documentation and error messages only, right?

**Comment by CalebJohn** [comment]
@nishantwrp that's correct.

**Comment by nishantwrp** [comment]
@CalebJohn does it look good now?

**Review by CalebJohn — APPROVED** [review]

**Comment by CalebJohn** [comment]
@nishantwrp that's not what I had in mind, but it works! Go ahead and merge.

**Pull request merged**
