### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by amandamcg**
Updating readme to further explain how variables work and clarify that templates are auto-imported.

### CODE REVIEW

**Comment by nishantwrp** [comment]
@amandamcg, thanks!. The rewrite looks good. I just have one doubt

- Should the legacy templates part be on the top? Because the new users will never know what legacy templates are. And that's not something actionable. (The complete process is automatic)

What do you think? 

cc: @CalebJohn @laurent22 what do you guys think?

**Comment by CalebJohn** [comment]
I'd say it makes sense to have at the top for now, this is a period of transition so most users will welcome information like that. After a few weeks you can move the information somewhere less prominent to reflect the fact that less users will be coming from the old system. 
Ultimately, it's up to you @nishantwrp because you'll be the one making the change.

**Review by nishantwrp — APPROVED** [review]
Got your point @CalebJohn. Makes sense, merging.

**Comment by tessus** [comment]
I thought it only shows up, when someone is actually using legacy templates. Thus this shouldn't matter.

**Comment by amandamcg** [comment]
@tessus this edit was on the plugin main README, so everyone will see it. @CalebJohn I agree it makes sense to move it after transition period. @nishantwrp, maybe you could even change it from "Legacy Templates" to users of Joplin X.X.X or earlier, that way it is clear it only applies to older versions in the meantime.

**Comment by tessus** [comment]
@amandamcg my bad. I mixed this up with the notification in the desktop app.

> maybe you could even change it from "Legacy Templates" to "users of Joplin X.X.X or earlier", that way it is clear it only applies to older versions.

I think this is a good idea. Maybe even use the term legacy templates in brackets: `users of Joplin X.X.X or earlier (legacy templates)`

**Pull request merged**
